# Generated by Django 2.1.7 on 2019-06-16 11:04

import customUser.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Эл. почта')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Вип?')),
                ('clientFio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('clientCompany', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фирма')),
                ('clientSite', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес сайта')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('post_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Индекс')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_allow_email', models.BooleanField(default=True, verbose_name='Согласен на рассылку')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', customUser.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='callBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('clientPhone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('clientEmail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('clientSite', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес сайта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий по клиенту')),
                ('is_done', models.BooleanField(default=False, verbose_name='Заявка отработана ?')),
                ('is_client', models.BooleanField(default=False, verbose_name='Возможна дальнейшая работа ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
            ],
            options={
                'verbose_name': 'Заявка на обратный звонок',
                'verbose_name_plural': 'Заявки на обратный звонок',
            },
        ),
        migrations.CreateModel(
            name='quizForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step0', models.CharField(blank=True, max_length=30, null=True, verbose_name='Сколько заявок?')),
                ('step1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Какой бюджет?')),
                ('step2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название сайта/Группы')),
                ('step3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Какие услуги интересны?')),
                ('step4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сфера деятельности')),
                ('is_done', models.BooleanField(default=False, verbose_name='Заявка отработана ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Квиз форма',
                'verbose_name_plural': 'Квиз формы',
            },
        ),
    ]
