# Generated by Django 2.1.7 on 2019-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Заявка на обратный звонок', 'verbose_name_plural': 'Заявки на обратный звонок'},
        ),
        migrations.AlterField(
            model_name='callback',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий по клиенту'),
        ),
    ]
