# Generated by Django 2.1.7 on 2019-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0002_auto_20190310_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step0', models.CharField(blank=True, max_length=30, null=True, verbose_name='Сколько заявок?')),
                ('step1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Какой бюджет?')),
                ('step2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название сайта/Группы')),
                ('step3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Какие услуги интересны?')),
                ('step4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сфера деятельности')),
                ('is_done', models.BooleanField(default=False, verbose_name='Заявка отработана ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Квиз форма',
                'verbose_name_plural': 'Квиз формы',
            },
        ),
    ]
