# Generated by Django 2.1.7 on 2019-06-16 11:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=255, verbose_name='Заголовок услуги')),
                ('serviceNameSmall', models.CharField(max_length=255, verbose_name='Подзаголовок услуги')),
                ('serviceImage', models.ImageField(upload_to='services/', verbose_name='Картинка')),
                ('serviceInfo', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('servicePrice', models.CharField(default='', max_length=255, verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показывать услугу?')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewFromCompany', models.CharField(blank=True, max_length=255, null=True, verbose_name='От кого отзыв (фирма)')),
                ('reviewFromMan', models.CharField(blank=True, max_length=255, null=True, verbose_name='От кого отзыв (руководитель)')),
                ('reviewFromSite', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('image', models.ImageField(upload_to='showcases/', verbose_name='Картинка')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('showHomePage', models.BooleanField(default=False, verbose_name='Показывать на главной?')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='showCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.CharField(max_length=255, verbose_name='Заголовок кейса')),
                ('caseNameSlug', models.CharField(blank=True, max_length=255, verbose_name='Заголовок кейса')),
                ('siteUrl', models.CharField(max_length=255, verbose_name='Адрес сайта')),
                ('image', models.ImageField(upload_to='showcases/', verbose_name='Картинка')),
                ('showcaseInfo', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('showcaseFullInfo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание ')),
                ('showInHomePage', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный кейс?')),
                ('caseType', models.CharField(choices=[('CO', 'Контекстная реклама'), ('SE', 'СЕО продвижение'), ('TA', 'Таргетированная релама'), ('SI', 'Создание сайтов')], default='CO', max_length=2, verbose_name='Тип кейса')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
    ]
