# Generated by Django 2.1.7 on 2019-06-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sites/', verbose_name='Картинка сайта')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
    ]
