# Generated by Django 2.1.7 on 2019-03-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewFromCompany', models.CharField(blank=True, max_length=255, null=True, verbose_name='От кого отзыв (фирма)')),
                ('reviewFromMan', models.CharField(blank=True, max_length=255, null=True, verbose_name='От кого отзыв (руководитель)')),
                ('reviewFromSite', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('image', models.ImageField(upload_to='showcases/', verbose_name='Картинка')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('showHomePage', models.BooleanField(default=False, verbose_name='Показывать на главной?')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
