# Generated by Django 2.1.7 on 2019-06-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0002_oursites'),
    ]

    operations = [
        migrations.AddField(
            model_name='allservices',
            name='serviceTarget',
            field=models.CharField(blank=True, max_length=255, verbose_name='Код цели яндекс'),
        ),
    ]
