# Generated by Django 2.1.7 on 2019-04-18 20:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0003_showcase_showcasefullinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='allServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=255, verbose_name='Заголовок услуги')),
                ('serviceNameSmall', models.CharField(max_length=255, verbose_name='Подзаголовок услуги')),
                ('serviceImage', models.ImageField(upload_to='services/', verbose_name='Картинка')),
                ('serviceInfo', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('servicePrice', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Стоимость услуги')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показывать услугу?')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
