# Generated by Django 2.1.7 on 2019-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0004_allservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allservices',
            name='servicePrice',
            field=models.CharField(default='', max_length=255, verbose_name='Стоимость'),
        ),
    ]
